

CREATE_SCANS_TABLE = """
CREATE TABLE IF NOT EXISTS scans (
id INTEGER PRIMARY KEY,
date TEXT NOT NULL UNIQUE,
overall_score INTEGER NOT NULL,
notes TEXT
)
"""


CREATE_BODY_PART_READING_TABLE = """
CREATE TABLE IF NOT EXISTS body_part_reading (
id INTEGER PRIMARY KEY,
scan_id INTEGER NOT NULL,
body_part TEXT NOT NULL,
score INTEGER NOT NULL,
FOREIGN KEY (scan_id) REFERENCES scans(id)
)
"""


CREATE_STRESS_DECREASE_TABLE = """
CREATE TABLE IF NOT EXISTS stress_manager (
id INTEGER PRIMARY KEY,
stress_level INTEGER NOT NULL,
strategy_name TEXT NOT NULL,
strategy_description TEXT NOT NULL
)
"""