langs = [{"English": {
    'app_title': "Body Scan Log",
    'menu_title': "MENU",
    'add_menu_opt': "ADD NEW ENTRY",
    'view_all_menu_optn': "VIEW ALL ENTRIES",
    'analyze_menu_opt': "ANALYZE ENTRIES",
    'settings_menu_opt': "SETTINGS",
    'new_entry_title': "NEW ENTRY",
    'date_label': "DATE (YYYY-MM-DD):",
    'notes_label': "NOTES:",
    'submit_button': "SUBMIT ENTRY",
    'jaw': "JAW",
    "face": "FACE",
    "neck": "NECK",
    "upper back": "UPPER BACK",
    "mid back": "MID BACK",
    "lower back": "LOWER BACK",
    "left shoulder": "LEFT SHOULDER",
    "right shoulder": "RIGHT SHOULDER",
    "left arm": "LEFT ARM",
    "right arm": "RIGHT ARM",
    "chest": "CHEST",
    "stomach": "STOMACH",
    "left leg": "LEFT LEG",
    "right leg": "RIGHT LEG",
    "left foot": "LEFT FOOT",
    "right foot": "RIGHT FOOT",
    "back_button": "BACK",
    "exit_button": "EXIT",
    "settings": "SETTINGS",
    "lang_option": "LANGUAGES",
    "Stress decreasing strategies": "STRESS DECREASE STRATEGIES",
    "COPING STRATEGIES": "COPING STRATEGIES",
    "Strategies for mild stress:": "MILD STRESS STRATEGIES:",
    "Strategies for mid stress:": "MODERATE STRESS STRATEGIES:",
    "Strategies for high stress:": "HIGH STRESS STRATEGIES:",
    "Mild stress strategies": "MILD STRESS STRATEGIES",
    "Mid stress strategies": "MODERATE STRESS STRATEGIES",
    "High stress strategies": "HIGH STRESS STRATEGIES",
    "Add Strategy": "ADD STRATEGY",
    "Edit Strategy": "EDIT STRATEGY",
    "Delete Strategy": "DELETE STRATEGY",
    "option_choice": "SELECT",
    "strategy_options_menu_default": "OPTIONS",
    "Add new strategy": "Add new strategy",
    "Strategy Name": "Strategy Name",
    "Strategy Description": "Strategy Description",
    "submit_strategy": "SUBMIT STRATEGY",
    "View Strategy": "VIEW STRATEGY",
    "SELECT AN OPTION": "SELECT AN OPTION",
    "about": "ABOUT",
    "ALL ENTRIES": "ALL ENTRIES",
    "see_more_button": "SEE DETAILS",
    "last_week_average": "LAST WEEK AVERAGE",
    "get_strategy_button": "GET A STRESS MANAGEMENT TECHNIQUE",
    "show_graph_button": "SHOW GRAPH",
    "graph_label": "GRAPH",
    "select_theme": "SELECT THEME",
    "Default": "Default",
    "Dark": "Dark",
    "Light": "Light",
    "Dyslexia": "Dyslexia",
    "name_error_title": "This strategy name already exists",
    "name_error_message": "Please change the strategy name and try again",
    "pref_db_error_title": "Save Failed",
    "pref_db_error_message": "Something went wrong while saving your preference. Please try again.",
    "entry_duplicate_entry_title": "Duplicate error",
    "entry_duplicate_entry_message": "An entry for this date already exists.",
    "entry_db_error_title": "Something Failed",
    "entry_db_error_message": "Something went wrong while saving entry. Please try again.",
    "get_strategy_error_title": "Something went wrong",
    "get_strategy_error_message": "Check if you have available strategies in settings.",
    "get_last_week_error_title": "Something went wrong",
    "get_last_week_error_message":"Couldn't find entries from the past 10 dasy",
    "delete_error_title": "Something went wrong.",
    "delete_error_message": "Could't delete strategy, please try again.",
    "edit_error_title": "Something went wrong.",
    "edit_error_message": "Couldn't save changes.",
    "db_error_ordered_rec_title": "Something went wrong.",
    "db_error_ordered_rec_message": "Couldn't get entries, please try again.",
    "db_error_rec_message": "Couldn't find entry. Please try again.",
}},
    {"Polski": {
        'app_title': "Dziennik Skanowania Ciała",
        'menu_title': "MENU",
        'add_menu_opt': "DODAJ NOWY WPIS",
        'view_all_menu_optn': "WSZYSTKIE WPISY",
        'analyze_menu_opt': "ANALIZA WPISÓW",
        'settings_menu_opt': "USTAWIENIA",
        'new_entry_title': "NOWY WPIS",
        'date_label': "DATA (RRRR-MM-DD)",
        'notes_label': "NOTATKI:",
        'submit_button': "ZAPISZ",
        'jaw': "SZCZĘKA",
        "face": "TWARZ",
        "neck": "SZYJA",
        "upper back": "GÓRNA CZĘŚĆ PLECÓW",
        "mid back": "ŚRODKOWA CZĘŚĆ PLECÓW",
        "lower back": "DOLNA CZĘŚĆ PLECÓW",
        "left shoulder": "LEWE RAMIĘ",
        "right shoulder": "PRAWE RAMIĘ",
        "left arm": "LEWA RĘKA",
        "right arm": "PRAWA RĘKA",
        "chest": "KLATKA PIERSIOWA",
        "stomach": "BRZUCH",
        "left leg": "LEWA NOGA",
        "right leg": "PRAWA NOGA",
        "left foot": "LEWA STOPA",
        "right foot": "PRAWA STOPA",
        "back_button": "POWRÓT",
        "exit_button": "WYJŚCIE",
        "settings": "USTAWIENIA",
        "lang_option": "JĘZYK",
        "Stress decreasing strategies": "STRATEGIE PRZECIWSTRESOWE",
        "COPING STRATEGIES": "STRATEGIE RADZENIA SOBIE",
        "Strategies for mild stress:": "STRATEGIE PRZY LEKKIM STRESIE:",
        "Strategies for mid stress:": "STRATEGIE PRZY UMIARKOWANYM STRESIE:",
        "Strategies for high stress:": "STRATEGIE PRZY SILNYM STRESIE:",
        "Mild stress strategies": "LEKKI STRES",
        "Mid stress strategies": "UMIARKOWANY STRES",
        "High stress strategies": "SILNY STRES",
        "Add Strategy": "DODAJ STRATEGIĘ",
        "Edit Strategy": "EDYTUJ STRATEGIĘ",
        "Delete Strategy": "USUŃ STRATEGIĘ",
        "option_choice": "WYBIERZ",
        "strategy_options_menu_default": "OPCJE",
        "Add new strategy": "DODAJ STRATEGIE",
        "Strategy Name": "NAZWA STRATEGII",
        "Strategy Description": "OPIS STRATEGII",
        "submit_strategy": "ZAPISZ STRATEGIE",
        "View Strategy": "ZOBACZ STRATEGIE",
        "SELECT AN OPTION": "WYBIERZ OPCJE",
        "about": "O APLIKACJI",
        "ALL ENTRIES": "WSZYSTKIE WPISY",
        "see_more_button": "POKAŻ WIĘCEJ",
        "last_week_average": "ŚREDNIA Z OSTATNICH 10 DNI",
        "get_strategy_button": "ZOBACZ LOSOWĄ STRATEGIĘ",
        "show_graph_button": "POKAŻ WYKRES",
        "graph_label": "WYKRES",
        "select_theme": "WYBIERZ MOTYW",
        "Default": "Domyślny",
        "Dark": "Ciemny",
        "Light": "Jasny",
        "Dyslexia": "Dysleksja",
        "name_error_title": "Ta nazwa strategi jest zajęta.",
        "name_error_message": "Wprowadz inną nazwe i sprubuj ponownie",
        "pref_db_error_title": "Nie udało się zapisać zmian",
        "pref_db_error_message": "Coś poszło nie tak podczas zapisywania zmian. Sprubuj ponownie.",
        "entry_duplicate_entry_title": "Wpis na tą date już istnieje",
        "entry_duplicate_entry_message": "Proszę wrowadz wpis pod inną datą",
        "entry_db_error_title": "Nie udało się zapisać zmian",
        "entry_db_error_message": "Coś poszło nie tak podczas zapisywania wpisu. Sprubuj ponownie.",
        "get_strategy_error_title": "Coś poszło nie tak",
        "get_strategy_error_message": "Sprawdź czy isnieją strategie w ustawieniach",
        "get_last_week_error_title": "Coś poszło nie tak",
        "get_last_week_error_message":"Nie znaleziono wpisów z ostatnich 10 dni",
        "delete_error_title": "Coś poszło nie tak",
        "delete_error_message": "Nie udało się usunąć strategi",
        "edit_error_title": "Coś poszło nie tak",
        "edit_error_message": "Nie udało się zapisać zmian",
        "db_error_ordered_rec_title": "Coś poszło nie tak",
        "db_error_ordered_rec_message": "Nie udało się znaleść wpisów. Sprubuj ponownie.",
    }},
]


class Translator:
    def __init__(self):
        self.dictionary = None
        self.lang = None
        self.available_languages = [
            "English",
            "Polski"
        ]


    def set_lang(self, lang):
        self.lang = lang
        self.get_dictionary(self.lang)


    def get_dictionary(self, lang):
        for i in langs:
            if lang in i:
                self.dictionary = i[lang]










